{% set name = "starlette-exporter" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlette_exporter-{{ version }}.tar.gz
  sha256: 3bde5d863effb26684210fe016a1ebf2b383efedf21a4b2f28585ec5064f4033

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - prometheus_client
    - python >=3.6
    - starlette

test:
  imports:
    - starlette_exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stephenhillier/starlette_exporter
  summary: Prometheus metrics exporter for Starlette applications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
    - ivergara
