{% set name = "starlette-exporter" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlette_exporter-{{ version }}.tar.gz
  sha256: b483354a387e3b1a31e07f414f19fa967996b3e480ad9f6042f142f273756b32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - prometheus_client
    - python >=3.6
    - starlette

test:
  imports:
    - starlette_exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stephenhillier/starlette_exporter
  summary: Prometheus metrics exporter for Starlette applications.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
    - ivergara
